# api/config/packages/api_platform.yaml
api_platform:
  mapping:
    paths:
      - "%kernel.project_dir%/src/Entity" # default configuration for annotations
      - "%kernel.project_dir%/config/api_platform" # yaml or xml directory configuration
  swagger:
    api_keys:
      JWT:
        name: Authorization
        type: header
