gesdinet_jwt_refresh_token:
  refresh_token_class: App\Entity\RefreshToken
  ttl: 2592000
  firewall: api
  return_expiration: true
  manager_type: orm
  single_use: false
  user_provider: app_user_provider
  user_identity_field: email
  cookie:
    enabled: true
    same_site: lax
    path: /
    domain: null
    http_only: true
    secure: true
    remove_token_from_body: true
