controllers:
  resource: ../src/Controller/
  type: annotation

kernel:
  resource: ../src/Kernel.php
  type: annotation

login:
  path: /api/login
  methods: ["POST"]

api_refresh_token:
  path: /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
api_token_invalidate:
  path: /api/token/invalidate
