# api/config/api_platform/resources.yaml
resources:
  App\Entity\Works: ~
  App\Entity\Medias: ~
  App\Entity\Movies: ~
  App\Entity\Diseases: ~
  App\Entity\Register:
    collectionOperations:
      register:
        method: "POST"
        path: "/register"
        controller: 'App\Controller\RegisterController::register'
        openapi_context:
          summary: "Register a new user"
          description: "Register a new user and send an activation email."
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email:
                      type: string
                      example: "vanaeca@hotmail.com"
                    password:
                      type: string
                      example: "123456"
                    firstname:
                      type: string
                      example: "Vanessa"
                    lastname:
                      type: string
                      example: "Carrillo"
                    birthday:
                      type: string
                      example: "12/12/1991"
