# api/config/api_platform/resources.yaml
resources:
  App\Entity\Works: ~
  App\Entity\Medias: ~
  App\Entity\Movies: ~
  App\Entity\Diseases: ~
  App\Entity\Register:
    collectionOperations:
      register:
        method: "POST"
        path: "/register"
        controller: 'App\Controller\RegisterController::register'
        openapi_context:
          summary: "Register a new user"
          description: "Register a new user and send an activation email."

        example: |
          {
              "email": "example@example.com",
              "password": "password123"
          }
App\Entity\Users:
  collectionOperations:
    login:
      method: "POST"
      path: "/login"
      controller: 'App\Controller\UsersController::login'
      openapi_context:
        summary: "Login"
        description: "Login and get a JWT token."

      example: |
        {
            "email": "example@example.com",
            "password": "password123"
        }
