# api/config/api_platform/resources.yaml
resources:
  App\Entity\Works: ~
  App\Entity\Medias: ~
  App\Entity\Movies: ~
  App\Entity\Diseases: ~
  # App\Controller\WorksController:
    attributes:
      normalization_context:
        groups: ["work:read"]
      denormalization_context:
        groups: ["work:write"]
    collectionOperations:
      get:
        method: "GET"
        path: "/works"
        controller: 'App\Controller\WorksController::getWorks'
        defaults:
          _api_resource_class: 'App\Entity\Works'
          _api_collection_operation_name: "getWorks"
      post:
        method: "POST"
        path: "/works"
        controller: 'App\Controller\WorksController::postWorks'
        defaults:
          _api_resource_class: 'App\Entity\Works'
          _api_collection_operation_name: "postWorks"
    itemOperations:
      get:
        method: "GET"
        path: "/works/{id}"
        controller: 'App\Controller\WorksController::getWork'
        defaults:
          _api_resource_class: 'App\Entity\Works'
          _api_item_operation_name: "getWork"
      put:
        method: "PUT"
        path: "/works/{id}"
        controller: 'App\Controller\WorksController::putWork'
        defaults:
          _api_resource_class: 'App\Entity\Works'
          _api_item_operation_name: "putWork"
      delete:
        method: "DELETE"
        path: "/works/{id}"
        controller: 'App\Controller\WorksController::deleteWork'
        defaults:
          _api_resource_class: 'App\Entity\Works'
          _api_item_operation_name: "deleteWork"
