# api/config/api_platform/resources.yaml
resources:
  App\Entity\Works: ~
  App\Entity\Medias: ~
  App\Entity\Movies: ~
  App\Entity\Contacts: ~                  
  App\Entity\Diseases: 
    operations:
      getAllDiseases:
        class: ApiPlatform\Metadata\GetCollection
        openapi:
          tags: ["Diseases"]
          responses: { 
            201: { description: "Get Diseases" } 
            400: { description: "Invalid Input" } 
            422: { description: "Unprocessable entity" } 
          }
          summary: Get All Diseases
          description: >
            # Get All Diseases 
  App\Entity\User:
    operations:
      create_user:
        class: ApiPlatform\Metadata\Post
        uriTemplate: "/createUser"
        controller: App\Controller\RegisterController::createRegister
        openapi:
          tags: ["Register"]
          responses: { 
            201: { description: "User create" } 
            400: { description: "Invalid Input" } 
            422: { description: "Unprocessable entity" } 
          }
          summary: Register to the application
          description: >
            # Register to the application
          requestBody:
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    email: { type: string }
                    password: { type: string }
                    firstname: { type: string }
                    lastname: { type: string }
                    birthday: { type: string }
                example:
                  email: joc4911@gmail.com
                  password: "123456"
                  firstname: Carlos
                  lastname: Carrillo
                  birthday: 12/12/1991
      # get_user:
      #   class: ApiPlatform\Metadata\Get
      #   uriTemplate: "/getUser"
      #   controller: App\Controller\UserController::getUser
       
