# api/config/api_platform/resources.yaml
resources:
  App\Entity\Works: ~
  App\Entity\Medias: ~
  App\Entity\Movies: ~
  App\Entity\Diseases: ~
  App\Controller\MailController:
    collectionOperations:
      post:
        method: "POST"
        path: "/mail"
        controller: 'App\Controller\MailController::index'
